"""Cross-runtime parity test. Asserts the Python framework produces byte-identical output to
the JavaScript framework for every public primitive at a fixed inner_w.

The reference fixture is generated by `node scripts/cli/lib/__tests__/dump_reference.js` and
checked into the repo at `scripts/python/sacred_cli/__tests__/fixtures/reference.json`. The
`npm run test:python` script regenerates the fixture before running this suite so any JS-side
drift is captured before the assertions fire here. If the JS source is the cause of failure,
re-run `npm test` after porting the change to the Python mirror; if Python is the cause, fix
the Python module to mirror its JS counterpart.
"""

import json
import os
import unittest

from . import _bootstrap  # noqa: F401

from sacred_cli.button import button, button_row
from sacred_cli.card import (
    card_bot,
    card_header_row,
    card_row,
    card_select_row,
    card_top,
    word_wrap,
)
from sacred_cli.table import format_row, kv_table, kv_table_gradient
from sacred_cli.window import (
    get_inner_width,
    shadow_bottom_row,
    wrap_line,
    wrap_line_top,
)

_HERE = os.path.dirname(os.path.abspath(__file__))
_FIXTURE_PATH = os.path.join(_HERE, "fixtures", "reference.json")

# NOTE(jimmylee): Mirror of dump_reference.js. The two specs MUST stay in lockstep.
COL_SPEC = [
    {"width": 10, "align": "left"},
    {"width": 12, "align": "left", "grow": True},
]

STATUS_COL_SPEC = [
    {"width": 10, "align": "left", "status": True},
    {"width": 10, "align": "right", "status": True, "gap": 2},
]


class TestParity(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        if not os.path.exists(_FIXTURE_PATH):
            raise unittest.SkipTest(
                f"Reference fixture missing at {_FIXTURE_PATH}. "
                "Run `node scripts/cli/lib/__tests__/dump_reference.js > "
                "scripts/python/sacred_cli/__tests__/fixtures/reference.json` first."
            )
        with open(_FIXTURE_PATH, "r", encoding="utf-8") as fh:
            cls.fixture = json.load(fh)
        cls.inner_w = cls.fixture["inner_w"]

    def test_card_top(self):
        self.assertEqual(card_top("TITLE", self.inner_w), self.fixture["card_top"])

    def test_card_row(self):
        self.assertEqual(card_row("hello", self.inner_w), self.fixture["card_row"])

    def test_card_bot(self):
        self.assertEqual(card_bot(self.inner_w), self.fixture["card_bot"])

    def test_card_select_row_off(self):
        self.assertEqual(
            card_select_row("item", self.inner_w, False),
            self.fixture["card_select_row_off"],
        )

    def test_card_select_row_on(self):
        self.assertEqual(
            card_select_row("item", self.inner_w, True),
            self.fixture["card_select_row_on"],
        )

    def test_card_header_row(self):
        composed = card_header_row(format_row(["A", "B"], COL_SPEC, self.inner_w), self.inner_w)
        self.assertEqual(composed, self.fixture["card_header_row"])

    def test_format_row_basic(self):
        self.assertEqual(
            format_row(["name", "value"], COL_SPEC, self.inner_w),
            self.fixture["format_row_basic"],
        )

    def test_format_row_status(self):
        self.assertEqual(
            format_row(["ACTIVE", "PAID"], STATUS_COL_SPEC, self.inner_w),
            self.fixture["format_row_status"],
        )

    def test_button_esc(self):
        self.assertEqual(button("ESC", "exit"), self.fixture["button_esc"])

    def test_button_arrow(self):
        self.assertEqual(button("\u21B5", "select"), self.fixture["button_arrow"])

    def test_button_row(self):
        composed = button_row(button("ESC", "exit"), button("\u21B5", "select"), self.inner_w)
        self.assertEqual(composed, self.fixture["button_row"])

    def test_word_wrap(self):
        self.assertEqual(
            word_wrap("the quick brown fox jumps over the lazy dog", 12),
            self.fixture["word_wrap"],
        )

    def test_kv_table(self):
        self.assertEqual(
            kv_table([("PROJECT", "sacred"), ("STATUS", "OK")]),
            self.fixture["kv_table"],
        )

    def test_kv_table_gradient(self):
        self.assertEqual(
            kv_table_gradient([("STATUS", "OK")]),
            self.fixture["kv_table_gradient"],
        )

    def test_inner_width_80(self):
        self.assertEqual(get_inner_width(80), self.fixture["inner_width_80"])

    def test_wrap_line_top(self):
        self.assertEqual(
            wrap_line_top("content", self.inner_w),
            self.fixture["wrap_line_top"],
        )

    def test_wrap_line(self):
        self.assertEqual(wrap_line("content", self.inner_w), self.fixture["wrap_line"])

    def test_shadow_bottom_row(self):
        self.assertEqual(shadow_bottom_row(self.inner_w), self.fixture["shadow_bottom_row"])


if __name__ == "__main__":
    unittest.main()
